## Hydra Settings ##
defaults:  
  - _self_  
  - override hydra/hydra_logging: disabled  
  - override hydra/job_logging: disabled  

hydra:
  run:
    dir: .
  output_subdir: null
  sweep:
    dir: .
    subdir: .


## WanDB Settings ##
wandb:
    project: pml-pl-defect
    run_name: ''
    tags: [200 epochs]
    notes: ''
    data_dir: ${img_dir}
    model_name: 'convnext_base'


## User Settings ##
img_dir: '/content/drive/MyDrive/Colab Notebooks/pml_pl_defect/input/train_data'
train_master_dir: '/content/drive/MyDrive/Colab Notebooks/pml_pl_defect/input/train.csv'
save_model_dir: '/content/drive/MyDrive/Colab Notebooks/pml_pl_defect/model'
num_classes: 2
embedding_size: 512
image_size: 224
seed: 0


train_test_split:
    test_size: 0.25
    random_state: 42

train_dataloader:
    batch_size: 4
    shuffle: True
    num_workers: 2
    pin_memory: True

val_dataloader:
    batch_size: 1
    shuffle: False # DO NOT CHANGE!!!
    num_workers: 2
    pin_memory: True
  
train_transform:
    resize:
        image_size: ${image_size}
    random_horizontal_flip:
        p: 0.5
    random_vertical_flip:
        p: 0.5
    random_rotation:
        degrees: 20
    random_affine:
        degrees: [-90, 90]
        translate: [0, 0]
        scale: [1.0, 1.0]
        shear: [-0.2, 0.2]
    color_jitter:
        brightness: 0.1
        contrast: 0.1
        saturation: 0.1
        hue: 0
    normalize:
        mean: [0.485, 0.456, 0.406]
        std: [0.229, 0.224, 0.225]

test_transform:
    resize:
        image_size: ${image_size}
    normalize:
        mean: [0.485, 0.456, 0.406]
        std: [0.229, 0.224, 0.225]

model:
    model_name: convnext_base
    pretrained: True

loss_fn:
    name: ArcFaceLoss

optimizer:
    name: Adam
    adam:
        lr: 1e-4
        weight_decay: 1e-5
    sgd:
        lr: 1e-4
        weight_decay: 1e-5

callbacks:
    early_stopping:
        enable: True
        monitor: 'val_loss'
        patience: 20
        mode: 'min'
    model_checkpoint:
        enable: True
        monitor: 'val_loss'
        mode: 'min'
        save_top_k: 1
        save_last: False

trainer:
    max_epochs: 200
    gpus: 1
    auto_lr_find: True
    deterministic: True